"""Phase 3 (Option B): Learned early stopping for latent thoughts.

Instead of a fixed m for all debate turns, train a lightweight classifier
that predicts "has this agent's reasoning converged?" at each latent step.
If yes, stop and transfer working memory. This directly reduces decode-
equivalent steps (and therefore energy) without changing the model's
per-step reasoning quality.

Architecture: 2-layer MLP on h_t → sigmoid(stop_probability)
  Input: h_t ∈ R^d (last-layer hidden state at current step)
  Output: p(stop) ∈ [0, 1]
  Stop when p(stop) > threshold (tunable)

Training data: generated by Phase 1 (latentmas_baseline.py).
  For each (task, m) pair, we know the final agreement with text baseline.
  Label: step i is "sufficient" if agreement at step i ≈ agreement at step m.
  Concretely: run each task at m=80, record h_t and B's agreement at each
  step i ∈ {5, 10, 15, ..., 80}. The earliest step where agreement stabilizes
  (within ε of final) is the optimal stopping point.

This script:
  1. Generates training data: runs latent thoughts at m=80, checkpointing
     h_t and B-agreement every 5 steps.
  2. Trains the stop classifier.
  3. Evaluates: how much does adaptive stopping reduce m at matched accuracy?

Outputs:
  results/latent_pilot/early_stop_training_data.jsonl
  results/latent_pilot/early_stop_classifier.pt
  results/latent_pilot/early_stop_summary.json
"""
from __future__ import annotations

import argparse
import copy
import random
import sys
import time
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, str(Path(__file__).parent.parent))
from latent_pilot.latentmas_baseline import (  # noqa: E402
    QWEN3_MODEL_ID,
    _cache_seq_len,
    apply_alignment,
    compute_alignment,
    generate_text_with_cache,
    load_qwen3,
    sample_pairs,
)
from latent_pilot.utils import (  # noqa: E402
    append_jsonl,
    results_root,
    save_json,
    top1_agreement,
)


class StopClassifier(nn.Module):
    """2-layer MLP: h_t [d] → p(stop) [1]."""

    def __init__(self, hidden_dim: int = 4096, bottleneck: int = 256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(hidden_dim, bottleneck),
            nn.ReLU(),
            nn.Linear(bottleneck, 1),
        )

    def forward(self, h: torch.Tensor) -> torch.Tensor:
        return torch.sigmoid(self.net(h.float()))


def generate_training_data(
    model, tok, W_e: torch.Tensor, target_norm: float,
    pairs: list[dict], max_m: int = 80, checkpoint_interval: int = 5,
) -> tuple[list[dict], torch.Tensor]:
    """For each pair, run latent thoughts up to max_m, checkpointing Agent B's
    agreement with text baseline every checkpoint_interval steps.

    Returns:
      records: list of dicts with {pair_idx, step, agreement, is_converged}
      h_t_bank: [N, hidden_dim] tensor of hidden states at each checkpoint
    """
    dev = next(model.parameters()).device
    hidden_dim = W_e.shape[0]
    records = []
    h_t_list = []  # store full h_t vectors for the classifier

    for pair_idx, pair in enumerate(pairs):
        try:
            # Text baseline (one-time per pair)
            b_text_prompt = (
                pair["system"] + "\n"
                + "Prior agent said:\n" + pair["a_text"] + "\n"
                + pair["b_hint"]
            )
            bt_enc = tok(b_text_prompt, return_tensors="pt", truncation=True, max_length=4096)
            with torch.no_grad():
                bt_out = model(
                    input_ids=bt_enc.input_ids.to(dev),
                    attention_mask=bt_enc.attention_mask.to(dev),
                    use_cache=False, return_dict=True,
                )
            logits_text = bt_out.logits[:, -1, :].float().cpu()

            # Agent A: run latent thoughts incrementally, checkpoint every interval
            a_input = pair["system"] + "\n" + pair["user"] + "<think>"
            a_enc = tok(a_input, return_tensors="pt", truncation=True, max_length=2048)
            a_ids = a_enc.input_ids.to(dev)

            with torch.no_grad():
                out = model(input_ids=a_ids, use_cache=True, output_hidden_states=True, return_dict=True)
            kv_cache = out.past_key_values
            h_t = out.hidden_states[-1][:, -1:, :]

            pair_records_start = len(records)

            for step in range(1, max_m + 1):
                e_next = apply_alignment(h_t, W_e, target_norm)
                with torch.no_grad():
                    step_out = model(
                        inputs_embeds=e_next,
                        past_key_values=kv_cache,
                        use_cache=True,
                        output_hidden_states=True,
                        return_dict=True,
                    )
                kv_cache = step_out.past_key_values
                h_t = step_out.hidden_states[-1][:, -1:, :]

                if step % checkpoint_interval == 0:
                    b_prompt = pair["system"] + "\n" + pair["b_hint"]
                    b_enc = tok(b_prompt, return_tensors="pt", truncation=True, max_length=2048)
                    b_cache = copy.deepcopy(kv_cache)
                    logits_latent = generate_text_with_cache(model, tok, b_cache, b_enc.input_ids.to(dev))
                    agree = top1_agreement(logits_text.unsqueeze(1), logits_latent.unsqueeze(1))

                    records.append({
                        "pair_idx": pair_idx,
                        "step": step,
                        "agreement": agree,
                    })
                    h_t_list.append(h_t.squeeze(0).squeeze(0).float().cpu())

            # Label convergence: step is converged if agreement within ε of final
            pair_recs = records[pair_records_start:]
            if pair_recs:
                final_agree = pair_recs[-1]["agreement"]
                for rec in pair_recs:
                    rec["final_agreement"] = final_agree
                    rec["is_converged"] = float(abs(rec["agreement"] - final_agree) < 0.1)

        except Exception as e:
            print(f"[pair {pair_idx}] error: {e}")
            import traceback; traceback.print_exc()
            continue

        if (pair_idx + 1) % 5 == 0:
            print(f"  [{pair_idx+1}/{len(pairs)}] generated {len(records)} checkpoint records")

    h_t_bank = torch.stack(h_t_list) if h_t_list else torch.zeros(0, hidden_dim)
    return records, h_t_bank


def train_classifier(
    records: list[dict], h_t_bank: torch.Tensor,
    hidden_dim: int = 4096, epochs: int = 100, lr: float = 1e-3,
) -> StopClassifier:
    """Train the stop classifier on full h_t vectors.

    Features: h_t ∈ R^hidden_dim (full last-layer hidden state at each checkpoint).
    Labels: is_converged (binary — agreement within ε of final).

    This learns per-task convergence detection from the hidden state's
    semantic content, not just step count or norm.
    """
    assert len(records) == h_t_bank.shape[0], (
        f"records ({len(records)}) and h_t_bank ({h_t_bank.shape[0]}) must match"
    )

    clf = StopClassifier(hidden_dim=hidden_dim, bottleneck=256)
    optimizer = torch.optim.Adam(clf.parameters(), lr=lr)

    features = h_t_bank  # [N, hidden_dim]
    labels = torch.tensor([r["is_converged"] for r in records], dtype=torch.float32).unsqueeze(1)

    for epoch in range(epochs):
        pred = clf(features)
        loss = F.binary_cross_entropy(pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if (epoch + 1) % 20 == 0:
            acc = ((pred > 0.5).float() == labels).float().mean()
            print(f"  epoch {epoch+1}: loss={loss.item():.4f} acc={acc.item():.3f}")

    return clf


def evaluate_early_stopping(
    records: list[dict], h_t_bank: torch.Tensor, clf: StopClassifier,
    threshold: float = 0.5,
) -> dict:
    """Simulate early stopping: for each pair, find the first checkpoint
    where the classifier predicts stop. Compare m_adaptive vs m_fixed."""
    with torch.no_grad():
        stop_probs = clf(h_t_bank).squeeze(1)

    pairs = {}
    for rec, sp in zip(records, stop_probs.tolist()):
        idx = rec["pair_idx"]
        if idx not in pairs:
            pairs[idx] = {"checkpoints": [], "final_agreement": rec.get("final_agreement", 0)}
        pairs[idx]["checkpoints"].append({
            "step": rec["step"],
            "agreement": rec["agreement"],
            "stop_prob": sp,
        })

    m_fixed_total = 0
    m_adaptive_total = 0
    agree_adaptive_total = 0
    n = 0

    for idx, p in pairs.items():
        ckpts = sorted(p["checkpoints"], key=lambda x: x["step"])
        m_fixed = ckpts[-1]["step"]
        m_adaptive = m_fixed  # default: no early stop
        agree_at_stop = ckpts[-1]["agreement"]

        for ck in ckpts:
            if ck["stop_prob"] > threshold:
                m_adaptive = ck["step"]
                agree_at_stop = ck["agreement"]
                break

        m_fixed_total += m_fixed
        m_adaptive_total += m_adaptive
        agree_adaptive_total += agree_at_stop
        n += 1

    return {
        "n_pairs": n,
        "m_fixed_mean": m_fixed_total / max(n, 1),
        "m_adaptive_mean": m_adaptive_total / max(n, 1),
        "m_reduction_pct": (1 - m_adaptive_total / max(m_fixed_total, 1)) * 100,
        "agreement_at_adaptive_stop": agree_adaptive_total / max(n, 1),
        "threshold": threshold,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-pairs", type=int, default=30)
    ap.add_argument("--max-m", type=int, default=80)
    ap.add_argument("--checkpoint-interval", type=int, default=5)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    out_dir = results_root()
    out_dir.mkdir(parents=True, exist_ok=True)

    model, tok = load_qwen3()
    dev = next(model.parameters()).device

    print("Computing alignment matrix...")
    W_e, target_norm = compute_alignment(model)

    pairs = sample_pairs(args.n_pairs, seed=args.seed)
    print(f"Generating training data: {len(pairs)} pairs, max_m={args.max_m}, "
          f"checkpoints every {args.checkpoint_interval} steps")

    # Step 1: Generate training data
    t0 = time.time()
    records, h_t_bank = generate_training_data(
        model, tok, W_e, target_norm, pairs,
        max_m=args.max_m, checkpoint_interval=args.checkpoint_interval,
    )
    print(f"Generated {len(records)} records, h_t_bank shape: {h_t_bank.shape}, "
          f"in {time.time()-t0:.1f}s")

    # Save training data
    data_path = out_dir / "early_stop_training_data.jsonl"
    if data_path.exists():
        data_path.unlink()
    for rec in records:
        append_jsonl(rec, data_path)
    torch.save(h_t_bank, out_dir / "early_stop_h_t_bank.pt")

    if not records:
        print("No training data generated")
        return

    # Step 2: Train classifier on full h_t vectors
    hidden_dim = h_t_bank.shape[1] if h_t_bank.dim() == 2 else 4096
    print(f"\nTraining stop classifier (hidden_dim={hidden_dim})...")
    clf = train_classifier(records, h_t_bank, hidden_dim=hidden_dim)

    clf_path = out_dir / "early_stop_classifier.pt"
    torch.save(clf.state_dict(), clf_path)
    print(f"Saved classifier to {clf_path}")

    # Step 3: Evaluate
    print("\nEvaluating early stopping...")
    results = {}
    for threshold in [0.3, 0.5, 0.7]:
        r = evaluate_early_stopping(records, h_t_bank, clf, threshold=threshold)
        results[f"threshold_{threshold}"] = r
        print(f"  threshold={threshold}: m_reduction={r['m_reduction_pct']:.1f}%, "
              f"agreement={r['agreement_at_adaptive_stop']:.3f}")

    # Step 4: Compute energy implications
    best_threshold = max(results, key=lambda k: results[k]["m_reduction_pct"])
    best = results[best_threshold]
    energy_per_step = 5.78  # J/decode-step from main project regression
    e_fixed = best["m_fixed_mean"] * energy_per_step
    e_adaptive = best["m_adaptive_mean"] * energy_per_step

    summary = {
        "n_pairs": len(pairs),
        "n_records": len(records),
        "per_threshold": results,
        "best_threshold": best_threshold,
        "energy_fixed_j_per_message": e_fixed,
        "energy_adaptive_j_per_message": e_adaptive,
        "energy_reduction_pct": (1 - e_adaptive / max(e_fixed, 0.01)) * 100,
    }
    save_json(summary, out_dir / "early_stop_summary.json")

    print(f"\n{'='*60}")
    print("EARLY STOPPING RESULTS")
    print(f"  Fixed m: {best['m_fixed_mean']:.0f} steps ({e_fixed:.0f} J/message)")
    print(f"  Adaptive m: {best['m_adaptive_mean']:.0f} steps ({e_adaptive:.0f} J/message)")
    print(f"  Reduction: {best['m_reduction_pct']:.1f}% fewer steps")
    print(f"  Energy saved: {e_fixed - e_adaptive:.0f} J/message ({summary['energy_reduction_pct']:.1f}%)")
    print(f"  Agreement at stop: {best['agreement_at_adaptive_stop']:.3f}")


if __name__ == "__main__":
    main()
